### ISSUE TITLE
`cargo install sqlx-models-cli` conflicts with `sqlx-cli`

### ISSUE THREAD

**Issue by mainrs** [tvallotton/models#12]
Maybe add an explanation that it conflicts with `sqlx-cli` in the readme :)

**Comment by tvallotton** [comment]
It is a superset of `sqlx-cli` as it is basically a fork of it. You can just replace it with: 
```
cargo install sqlx-models-cli --force
```
But I'll put a note in the readme with the explanation.

**Comment by tvallotton** [comment]
I've been thinking that this project doesn't need to be `sqlx` specific, so I decided that I will move it in the future to just `models`. In that case I will probably rename the CLI to `models`, and no conflict would occur.

**Comment by tvallotton** [comment]
The command is `models` now, so no conflict should occur.
