### ISSUE TITLE
Generate both `up` and `down` variants.

### ISSUE THREAD

**Issue by mainrs** [tvallotton/models#13]
Right now, the CLI does only generate the up variant. This could be achieved by using the same mechanism as `sqlx`: the `-r` flag.

**Comment by tvallotton** [comment]
I'm interested in this idea, but I'm not familiarized on how `sqlx-cli` distinguishes between an up and a down migration. Could you give me an example?

**Comment by tvallotton** [comment]
If I recall correctly, diesel creates a directory for each migration, with an `up.sql` and a `down.sql` file. That approach could work, but it wouldn't be compatible with `sqlx` AFAIK.

**Comment by mainrs** [comment]
`sqlx` does generate these as well. You have to specify the `-r` parameter though. See the help screen of the normal `sqlx` CLI.

**Comment by tvallotton** [comment]
It should now support down migrations using `models generate -r`
